Jh press schema changes
AMRC-FactoryPlus/schemas pull request #70
Opened 2024-10-31 12:32 UTC by JonHall101

Feedback from populating the press schema with data from the 1m press raised some slight changes to requirements. Press schema now includes an array of heaters to avoid the need for different devices using the same connection. Tool schema now includes arrays of pressure and temperature tags rather than single tags to allow for multiple sensors on a single tool.

2024-10-31 12:42 UTC, amrc-benmorrow requested changes

2024-10-31 12:42 UTC, amrc-benmorrow commented on Press/Press-v1.json
> +      "index": 0
Something has gone wrong here... were these exported from the Schema Editor?

2024-10-31 12:42 UTC, amrc-benmorrow commented on Press/Tool-v1.json
> -    "Pressure": {
Strictly speaking this is an incompatible change (a metric has been removed). Do we need some way to mark schemas as 'under development'?

2024-10-31 12:52 UTC, JonHall101 commented on Press/Press-v1.json
> +      "index": 0
yes, I've spotted that now. I'm just raising a new PR

2024-10-31 12:53 UTC, JonHall101 commented on Press/Tool-v1.json
> -    "Pressure": {
does it change anything that I am the only person using this (i appreciate this isn't best practice)

2024-10-31 13:27 UTC, amrc-benmorrow commented on Press/Tool-v1.json
> -    "Pressure": {
I think it should change things; but with these published publically we don't know who is or isn't using what. For now I think we don't worry, but we should either choose some way of marking schemas 'experimental: subject to breaking changes' or find a way to develop them privately.

2024-11-01 08:13 UTC, amrc-benmorrow approved these changes

2024-11-01 09:38 UTC, merged